version: '3.8'

services:
  php:
    build:
      context: .docker/php-fpm
    container_name: api-php
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: api-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./dist:/var/www/html/dist
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php

  db:
    image: mariadb:latest
    container_name: api-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
